# Generated by Django 3.2 on 2022-05-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220522_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='limit_rented_books',
            field=models.IntegerField(default=0),
        ),
    ]
