# Generated by Django 3.2 on 2022-05-26 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_limit_rented_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='limit_rented_books',
            new_name='rented_books',
        ),
    ]
