# Generated by Django 3.2 on 2022-05-22 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('0bd52224-1909-4f18-b85d-7fbf8ac000d9')),
        ),
    ]
