# Generated by Django 3.2 on 2022-05-22 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('65ada3ca-924b-47ed-9b63-304e673cf71f')),
        ),
    ]
