# Generated by Django 3.2 on 2022-05-22 03:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('9a6c306c-6811-401c-8bd6-859b45a34b71')),
        ),
    ]
