# Generated by Django 3.2 on 2022-05-22 04:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('c5ddcfe3-cce3-466c-ba4f-9368fe1501c7')),
        ),
    ]
