# Generated by Django 3.2 on 2022-05-22 04:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('e0c55da5-57cb-45e0-994d-010c126ae428')),
        ),
    ]
