# Generated by Django 3.2 on 2022-05-22 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('a0449648-33aa-42d0-a270-64c795b987c5')),
        ),
    ]
