# Generated by Django 3.2 on 2022-05-22 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220522_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('5e1c16a0-2c88-4d1a-b48e-fc1b6e92fb8f')),
        ),
    ]
