# Generated by Django 3.2 on 2022-05-22 04:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('c8494d44-828c-4e18-9cdd-360914bc3419')),
        ),
    ]
