# Generated by Django 3.2 on 2022-05-22 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('f40c930b-025b-40fe-b615-f4bcd8a1c974')),
        ),
    ]
