# Generated by Django 3.2 on 2022-05-22 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('608a3953-be9c-4c13-9066-d87e7c00c32b')),
        ),
    ]
