# Generated by Django 3.2 on 2022-05-22 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('18f02a23-b823-4930-8f59-2f26183d19be')),
        ),
    ]
