# Generated by Django 3.2 on 2022-05-24 01:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_book_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='des',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('3f5a5f2a-e31d-42a4-9bcf-6f2a0eb884fa')),
        ),
    ]
