# Generated by Django 3.2 on 2022-05-24 01:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20220524_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_of_publication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('71b38ea4-cb06-4d96-b976-f00ce1e9bd4e')),
        ),
    ]
