# Generated by Django 3.2 on 2022-05-24 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20220524_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('2c1a6f26-a1d2-487f-830d-4719ec8c99ca')),
        ),
    ]
