# Generated by Django 3.2 on 2022-05-25 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('a6b98dd9-78bc-41d7-939e-9d9638e8e062')),
        ),
    ]
