# Generated by Django 3.2 on 2022-05-25 02:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('1d05fa2f-4df5-4935-9dc7-c85cf6af6dbf')),
        ),
    ]
