# Generated by Django 3.2 on 2022-05-25 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('09a65c42-5f6a-43c2-bca1-f46a97620012')),
        ),
    ]
