# Generated by Django 3.2 on 2022-05-25 02:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('f2fcd8b3-99a0-4ea1-b9f7-9766af4b0bd0')),
        ),
    ]
