# Generated by Django 3.2 on 2022-05-25 02:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('93a2dcee-e291-4879-8e66-971a863f631d')),
        ),
    ]
