# Generated by Django 3.2 on 2022-05-25 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('e9ff3115-550b-46c4-90b1-c0d930d49bf7')),
        ),
    ]
