# Generated by Django 3.2 on 2022-05-26 01:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('237947a5-bce3-46f0-8625-0c5c48149635')),
        ),
    ]
