# Generated by Django 3.2 on 2022-05-26 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('a315da0e-e194-48eb-b297-36acbf1ab969')),
        ),
    ]
