# Generated by Django 3.2 on 2022-05-26 02:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('a7be0f42-3dcb-4705-9f6d-69d9cb55e637')),
        ),
    ]
