# Generated by Django 3.2 on 2022-05-27 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('1d372448-e60b-4068-bd51-0d21cbaf2de7')),
        ),
    ]
