# Generated by Django 3.2 on 2022-05-27 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('e10ef6f4-5dd8-4dd3-a8f4-5a1efab818fb')),
        ),
    ]
