# Generated by Django 3.2 on 2022-05-19 05:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_id', models.UUIDField(default=uuid.UUID('19a99733-3e35-45ea-ad53-39e128c5c75e'))),
                ('name', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(blank=True, to='book.Book')),
            ],
        ),
        migrations.CreateModel(
            name='RackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcase.rack')),
            ],
        ),
    ]
