# Generated by Django 3.2 on 2022-06-14 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='rack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookcase.rack'),
            preserve_default=False,
        ),
    ]
