# Generated by Django 3.2 on 2022-05-22 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('f9d89604-36e1-4e62-a101-154098098af3')),
        ),
    ]
