# Generated by Django 3.2 on 2022-05-22 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0002_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('74e18fb8-cd5a-4935-9f3f-b2b740034095')),
        ),
    ]
