# Generated by Django 3.2 on 2022-05-22 03:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0003_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('40ff6b51-7341-4456-b45e-f6969ceb8c9f')),
        ),
    ]
