# Generated by Django 3.2 on 2022-05-22 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookcase', '0004_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rackitem',
            name='current_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('e03da342-588d-47fe-82ed-3346b986c438')),
        ),
    ]
