# Generated by Django 3.2 on 2022-05-22 04:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220522_0440'),
        ('bookcase', '0007_auto_20220522_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('ce82f618-19b9-4db0-a421-db99682cb138')),
        ),
        migrations.DeleteModel(
            name='RackItem',
        ),
        migrations.AddField(
            model_name='bookitem',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookcase.rack'),
        ),
    ]
