# Generated by Django 3.2 on 2022-05-22 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookcase', '0008_auto_20220522_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('1fec2c2f-1cf5-4c55-a60c-29c7e9e4226c')),
        ),
    ]
