# Generated by Django 3.2 on 2022-05-22 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookcase', '0009_auto_20220522_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='stock',
            field=models.IntegerField(default=5, max_length=1),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('a146e8c0-a25f-478f-9fa4-f6c22e6fab87')),
        ),
    ]
