# Generated by Django 3.2 on 2022-05-22 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0010_auto_20220522_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='stock',
            field=models.IntegerField(default='5', max_length=1),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('a1e6de5a-36e7-4b81-a622-c2ab68586cc5')),
        ),
    ]
