# Generated by Django 3.2 on 2022-05-22 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookcase', '0011_auto_20220522_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='owner',
            field=models.ForeignKey(default='Library', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='stock',
            field=models.IntegerField(default=5, max_length=1),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('b648fedb-ecb6-4f62-9bdf-7bd5535d7dd9')),
        ),
    ]
