# Generated by Django 3.2 on 2022-05-24 01:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0013_auto_20220522_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('2d63c071-ab16-4391-bf15-f97bef914a88')),
        ),
    ]
