# Generated by Django 3.2 on 2022-05-24 01:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0014_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('caefd5c5-da40-420d-b89b-2f001b13f359')),
        ),
    ]
