# Generated by Django 3.2 on 2022-05-24 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0015_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('07f5b9ed-653e-4767-b42a-2fa54f77b31a')),
        ),
    ]
