# Generated by Django 3.2 on 2022-05-25 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_book_book_id'),
        ('bookcase', '0016_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='book.Book'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('026c2de8-278e-4b61-b889-89bca80649d5')),
        ),
    ]
