# Generated by Django 3.2 on 2022-05-25 02:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0017_auto_20220525_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='books',
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('3ec46e68-d938-459f-ad69-146c258b59d0')),
        ),
    ]
