# Generated by Django 3.2 on 2022-05-25 02:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0019_auto_20220525_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='id',
        ),
        migrations.AddField(
            model_name='bookitem',
            name='book_item_id',
            field=models.UUIDField(default=uuid.UUID('a1476573-7f61-4e1c-87b0-df136bf14e89'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('a3f93102-1a9a-4f00-875e-1a9966f59550')),
        ),
    ]
