# Generated by Django 3.2 on 2022-05-25 02:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0020_auto_20220525_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='book_item_id',
        ),
        migrations.AddField(
            model_name='bookitem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('de98d63e-6243-44cf-9330-fc78f47097ba')),
        ),
    ]
