# Generated by Django 3.2 on 2022-05-25 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0021_auto_20220525_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='owner',
            new_name='current_owner',
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('8070a9c4-677e-4b15-ae01-f085226f12e4')),
        ),
    ]
