# Generated by Django 3.2 on 2022-05-26 01:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0022_auto_20220525_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('790ef063-bcaf-45c8-8b6c-dc62bdaa5b9a')),
        ),
    ]
