# Generated by Django 3.2 on 2022-05-26 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0023_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('861280c1-3b9d-4a50-b794-f500772ff080')),
        ),
    ]
