# Generated by Django 3.2 on 2022-05-26 02:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0024_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('f54ce7d4-d3be-4dbd-b959-bf4dfae93b3d')),
        ),
    ]
