# Generated by Django 3.2 on 2022-05-27 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0026_alter_rack_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_id',
            field=models.UUIDField(default=uuid.UUID('b0578861-e740-4dce-bd42-b29717a82106')),
        ),
    ]
